spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    first:
      url: jdbc:mysql://localhost:3307/velox-sql-demo?useUnicode=true&characterEncoding=UTF8
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      username: root
    second:
      url: jdbc:mysql://localhost:3307/hgms?useUnicode=true&characterEncoding=UTF8
      driver-class-name: com.mysql.jdbc.Driver
      password: 123456
      username: root
logging:
  level:
    root: debug
velox-sql:
  global:
    table-prefix: tb_
    stand-table: true
    stand-column: true
    cache: true
    is-task-queue: true
server:
  tomcat:
    threads:
      max: 10000
